chore(table): updated stories
vmware-clarity/ng-clarity pull request #1222
Opened 2024-02-12 08:53 UTC by kanthvallampati

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-02-12 10:50 UTC, dtsanevmw requested changes
Looks good but add rowCount to 10 for all except the Basic one.

2024-02-13 09:10 UTC, kanthvallampati commented
@dtsanevmw 
Good catch! Let's set the rowCount to 10 for all, including the Basic one. This will allow us to showcase the variants more crisply. Plus, we'll still have controls to adjust the rowCount as needed.

2024-02-14 04:37 UTC, spadidapelli approved these changes

2024-02-14 07:42 UTC, dtsanevmw approved these changes

2024-02-14 09:13 UTC, merged