fix(a11y): return focus to datagrid detail pane toggle button after esc with zoom 250%
vmware-clarity/ng-clarity pull request #1408
Opened 2024-05-29 09:05 UTC by andyfeds

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: [CDE-2051](https://jira.eng.vmware.com/browse/CDE-2051)

## What is the new behavior?
Focus is returned to the button that opened the pane on ESC key in zoom more than 250%.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-05-29 10:22 UTC, sandeepkulki approved these changes

2024-05-29 13:57 UTC, sandeepkulki approved these changes

2024-05-29 18:07 UTC, kevinbuhmann requested changes
This PR appears to be a refactor/chore, not a fix. Please reword the title and summary. If this isn't needed, please close.

2024-05-30 07:50 UTC, andyfeds commented
> This PR appears to be a refactor/chore, not a fix. Please reword the title and summary. If this isn't needed, please close.

@kevinbuhmann this is a fix for a specific case where in the detail pane is closed using "ESC" key, the code needed to be moved into the service to fix it. It's needed. Let me know if i still need to refactor the title/summary.

2024-05-30 10:49 UTC, kevinbuhmann commented
> @kevinbuhmann this is a fix for a specific case where in the detail pane is closed using "ESC" key, the code needed to be moved into the service to fix it. It's needed. Let me know if i still need to refactor the title/summary.

Ah, I see. It appeared to be just a refactor, but the modal stack uses the service? I understand now.

2024-05-30 10:49 UTC, kevinbuhmann approved these changes

2024-05-30 11:46 UTC, merged