feat: pinnable and inline sidebar
vmware-clarity/ng-clarity pull request #1615
Opened 2024-11-12 11:17 UTC by Jinnie

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-11-28 12:01 UTC, valentin-mladenov reviewed
In Storybook dynamically changed `clrSidePanelSize`  while pinned doesn't affect/notify the container to resize itself.

2024-12-02 12:25 UTC, Jinnie commented on projects/angular/src/modal/modal.ts
> +        }
One is for setting pinned/unpinned, while the other handles side-by-side styles on open/close.
Check the screenshot for the undesired effect it resolves.
![image](https://github.com/user-attachments/assets/61d706d1-a6cc-477d-9139-0d0537522437)
The blank area on the left is where the sidebar will be displayed when opened.

I will add a check for `pinnable`, though it is not very likely that we change these runtime. Let's stay on the safe side.

2024-12-12 12:19 UTC, valentin-mladenov requested changes
Check my comments regarding side-panel logic in modal.

2024-12-12 12:19 UTC, valentin-mladenov commented on projects/angular/src/modal/modal.html
> +          </button>
Make no sense side-panel logic to be inside modal.

2024-12-12 12:19 UTC, valentin-mladenov commented on projects/angular/src/modal/modal.ts
> +
Make no sense side-panel logic to be inside modal.

2025-01-23 09:23 UTC, Jinnie commented on projects/angular/src/modal/modal.html
> +          </button>
done, moved to sidepanel.html

2025-01-23 09:23 UTC, Jinnie commented on projects/angular/src/modal/modal.ts
> +
done, moved to sidepanel.ts

2025-01-24 15:29 UTC, valentin-mladenov approved these changes
LGTM

Check my nit comment and reslove it when done.

2025-01-24 15:29 UTC, valentin-mladenov commented on projects/angular/src/modal/modal.ts
> +  @Input('clrModalSize') size: string;
try move it to the initial place
```suggestion
```

2025-01-27 11:44 UTC, merged