feat(datagrid): add option to disable column unsort
vmware-clarity/ng-clarity pull request #1617
Opened 2024-11-13 09:58 UTC by valentin-mladenov

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: CDE-2439

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-11-13 10:00 UTC, valentin-mladenov commented
follow up of #1612

2025-03-02 20:37 UTC, kevinbuhmann requested changes
See my comments. Please also update the PR summary.
1. It references a `clrDgEnableUnsortColumns` input that does not exist in the current revision.
2. It states that isn't a breaking change, but requiring application code to opt out of unsorting is a breaking change. If we want to release this as a non-breaking change, it needs to be an opt-in feature.

2025-03-02 20:37 UTC, kevinbuhmann commented on projects/angular/src/data/datagrid/datagrid-column.ts
> +      delete this._sortBy;
Does this just flatten the `if` blocks? Mixing such refactors with another significant code change can make the change harder to read and understand. Please extract this to a separate PR.

2025-03-02 20:37 UTC, kevinbuhmann commented on projects/angular/src/data/datagrid/datagrid-column.ts
> +        break;
This case should be moved back to it's original position to minimize this diff and make the change more obvious without have to mentally compare the code.

Further, there are actually two places with the unsorted/default case listed first. I have fixed both in a separate PR: #1721.

2025-03-02 20:37 UTC, kevinbuhmann commented on projects/angular/src/data/datagrid/datagrid-column.ts
> +  @Input('clrDgSortDisableUnsort') clrDgSortDisableUnsort = false;
```suggestion
  @Input('clrDgDisableUnsort') disableUnsort = false;
```

The input alias is redundant (has "sort" twice) and the property name doesn't need the `clrDg` prefix.

2025-04-08 08:11 UTC, valentin-mladenov commented on projects/angular/src/data/datagrid/datagrid-column.ts
> +      delete this._sortBy;
PR for the change #1777

2025-04-08 09:50 UTC, valentin-mladenov commented on projects/angular/src/data/datagrid/datagrid-column.ts
> +  @Input('clrDgSortDisableUnsort') clrDgSortDisableUnsort = false;
corrected in commit 8873189

2025-09-10 07:22 UTC, valentin-mladenov commented
WIll not be implemented

2025-09-29 11:44 UTC, merged