feat(number-picker): new component
vmware-clarity/ng-clarity pull request #1636
Opened 2024-12-05 09:19 UTC by dtsanevmw

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2025-01-07 12:35 UTC, valentin-mladenov requested changes
Check my comments.

2025-01-07 12:35 UTC, valentin-mladenov commented on projects/angular/src/forms/styles/_number-input.clarity.scss
> +        background-color: unset;
`+` and `-` should have some disabled color.

```suggestion
        fill: forms-variables.$clr-forms-text-disabled;
        background-color: unset;
```

2025-01-07 12:35 UTC, valentin-mladenov commented on projects/angular/src/forms/styles/_number-input.clarity.scss
> +        border: tokens.$cds-alias-object-border-width-100 solid tokens.$cds-alias-object-border-color;
`border` adds 2px to the width. Use `background-color`, `border-left` or `border-right`.

```suggestion
        background-color:  tokens.$cds-alias-object-border-color;
```

```suggestion
        border-left: tokens.$cds-alias-object-border-width-100 solid tokens.$cds-alias-object-border-color;
```

2025-01-07 12:35 UTC, valentin-mladenov commented on projects/angular/src/forms/styles/_input-group.clarity.scss
> +
Why is this section moved from it's original place?

2025-01-07 12:35 UTC, valentin-mladenov commented on projects/angular/src/forms/number-input/number-input-container.ts
> +    return this.input?.nativeElement.getAttribute('readonly') != null;
Readonly state doesn't behave properly.

Check it here: https://1636--storybook-clarity-design.netlify.app/demo/number-input?cds-theme=light

2025-01-07 12:37 UTC, valentin-mladenov commented
Prefixes and suffixes #1644 for number input must be validated. You can do that in sepaate PR.

2025-01-08 19:58 UTC, dtsanevmw commented on projects/angular/src/forms/styles/_input-group.clarity.scss
> +
It was overriding stuff that It shouldn't.

2025-01-09 15:24 UTC, valentin-mladenov approved these changes
Check my comments.

Additiopnally create a separate chore PR for implementing the new nuimber-input component in the `demo` and in datagrid number filter.

2025-01-09 15:24 UTC, valentin-mladenov commented on .storybook/stories/forms/forms-input-states-components.stories.ts
> +      </clr-number-input-container>
Make the same changes in other input stories `Required Mark`, `Reactive` and `Template Driven`.

2025-01-09 16:04 UTC, kevinbuhmann commented on projects/angular/src/forms/number-input/number-input-container.ts
> +    this.subscriptions.push(focusService.focusChange.subscribe(state => (this.focus = state)));
`prettier` will add the parentheses. I think statements should be wrapped in curly braces though `{}`.

2025-01-09 16:06 UTC, kevinbuhmann commented on projects/angular/src/forms/number-input/number-input-container.ts
> +    this.subscriptions.push(focusService.focusChange.subscribe(state => (this.focus = state)));
This should be in `ngOnInit`, not the constructor.

2025-01-09 16:08 UTC, kevinbuhmann commented on projects/angular/src/forms/number-input/number-input.ts
> +      event.preventDefault();
Just curious: What default behavior is being prevented here?

2025-01-09 16:11 UTC, kevinbuhmann commented on projects/angular/src/forms/number-input/number-input.ts
> +    el: ElementRef<HTMLInputElement>
```suggestion
    protected override el: ElementRef<HTMLInputElement>
```

If you override the `el` property here, you won't need to assert the `nativeElement` type below.

2025-01-09 16:11 UTC, kevinbuhmann commented on projects/angular/src/forms/number-input/number-input.ts
> +    const inputElement: HTMLInputElement = this.el.nativeElement as HTMLInputElement;
```suggestion
    const inputElement = this.el.nativeElement;
```

2025-01-09 16:11 UTC, kevinbuhmann commented on projects/angular/src/forms/number-input/number-input.ts
> +    const inputElement: HTMLInputElement = this.el.nativeElement as HTMLInputElement;
```suggestion
    const inputElement = this.el.nativeElement;
```

2025-01-09 16:15 UTC, kevinbuhmann commented on projects/angular/src/forms/input/input.ts
> +      console.warn(`Warning: Inputs of type "number" should utilize the number-input component for proper handling.\n
The datagrid number filter triggers this warning. That should be fixed.

http://localhost:4200/demo/datagrid/string-filtering?cds-theme=light

2025-01-09 16:18 UTC, kevinbuhmann requested changes
See my comments. We cannot merge this as is because there are warnings for non-user elements (datagrid number filter).

2025-01-10 15:04 UTC, dtsanevmw commented on projects/angular/src/forms/number-input/number-input.ts
> +      event.preventDefault();
I had it written differently and I supposed missed to removed it while moving it here. Thanks for catching!

2025-01-10 15:05 UTC, dtsanevmw commented on projects/angular/src/forms/number-input/number-input.ts
> +    return this.el?.nativeElement.getAttribute('readonly') !== null;
Same thing as mentioned above. Had it written differently and missed to remove it. Thanks!

2025-01-10 15:07 UTC, dtsanevmw commented on projects/angular/src/forms/number-input/number-input.ts
> +    const inputElement: HTMLInputElement = this.el.nativeElement as HTMLInputElement;
Not needed with the override of element variable and current setup.

2025-01-10 15:16 UTC, kevinbuhmann commented on projects/angular/src/forms/number-input/number-input-container.ts
> +    this.subscriptions.push(focusService.focusChange.subscribe(state => (this.focus = state)));
This matches existing coding patterns. We should change it everywhere in a separate PR.

2025-01-10 15:45 UTC, kevinbuhmann commented on projects/angular/src/data/datagrid/_datagrid.clarity.scss
> +      input {
Is there a class name that could be used here instead of the tag name?

2025-01-10 15:48 UTC, kevinbuhmann commented on projects/angular/src/forms/common/providers/control-class.service.ts
> +      element.classList.forEach(klass => {
This looks like an unrelated refactor?

2025-01-10 15:54 UTC, dtsanevmw commented on projects/angular/src/forms/common/providers/control-class.service.ts
> +      element.classList.forEach(klass => {
Yes! I reverted it but missed one more change...

2025-01-10 15:57 UTC, kevinbuhmann approved these changes

2025-01-13 15:31 UTC, merged