feat(file-input): add file list (advanced file picker)
vmware-clarity/ng-clarity pull request #1655
Opened 2024-12-20 15:27 UTC by kevinbuhmann

## PR Checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

Feature

## What is the current behavior?

There is no file input "advanced mode" that lists each selected file. The file input browse button text is always replaced with the selected file name or number of selected files. 

Issue Number: CDE-2489

## What is the new behavior?

There is a new file input "advanced mode" that lists each selected file. This is achieved by adding a `clr-file-list` to the `clr-file-input-container`.

## Does this PR introduce a breaking change?

No.

2025-01-08 09:11 UTC, valentin-mladenov commented
Label text color fix is merged with #1653

2025-01-09 16:00 UTC, kevinbuhmann commented
> Label text color fix is merged with #1653

@valentin-mladenov That fix doesn't work for `button.btn-link` elements. Adding `status="neutral"` to the clear file button icon fixes the bug in this PR though.

2025-01-10 14:52 UTC, valentin-mladenov reviewed
Check my comments.

2025-01-10 14:57 UTC, kevinbuhmann commented on .storybook/stories/file-input/advanced-file-input-states.stories.ts
> +      <div>${advancedFileInputTemplateFn('Long Filename')}</div>
These `div` elements are for the formatting. It gets weird without them.

2025-01-10 15:09 UTC, kevinbuhmann commented on projects/angular/src/forms/file-input/file-input-validator.ts
> +    const errors: ClrFileListValidationErrors = {};
I just added a more specific type, but the function still has the match the `Validator` interface.

2025-01-10 15:14 UTC, kevinbuhmann commented on projects/angular/src/forms/file-input/file-list.ts
> +              <cds-icon shape="times" status="neutral"></cds-icon>
I agree. Thanks!

2025-01-10 15:36 UTC, kevinbuhmann commented on projects/angular/src/forms/styles/_file-input.clarity.scss
> +      padding-left: tokens.$cds-global-space-2;
Without padding on the clear file button, it gets cut off for long filenames. I can reduce it to 1px though. That still looks fine with the other suggested changes.

2025-01-13 16:00 UTC, valentin-mladenov approved these changes
LGTM

I have only one comment.

2025-01-13 16:00 UTC, valentin-mladenov commented on projects/angular/src/forms/styles/_file-input.clarity.scss
> +      margin: 0;
Because `btn-icon` sets `min-width: 0` the button gets pushed out. Add `min-width: tokens.$cds-global-space-7;` to normalize it.

![image](https://github.com/user-attachments/assets/b104ab43-fd6f-4ed1-b238-3791369cc66b)

```suggestion
      min-width: tokens.$cds-global-space-7;
      margin: 0;
```

2025-01-13 16:07 UTC, kevinbuhmann commented on projects/angular/src/forms/styles/_file-input.clarity.scss
> +      margin: 0;
Thanks. I pushed this change.

2025-01-13 16:08 UTC, kevinbuhmann commented on projects/angular/src/forms/styles/_file-input.clarity.scss
> +      padding-left: tokens.$cds-global-space-2;
This is now pushed as well after https://github.com/vmware-clarity/ng-clarity/pull/1655#discussion_r1913412888.

2025-01-14 20:29 UTC, kevinbuhmann commented on projects/angular/src/forms/file-input/file-input-validator.ts
> +      .filter(type => !!type);
This PR should be merged after #1668.

2025-01-14 20:33 UTC, kevinbuhmann commented on projects/angular/src/forms/file-input/file-input-validator.ts
> +    const accept = fileInputElement.accept ? fileInputElement.accept.split(',').map(type => type.trim()) : null;
This PR should be merged after #1668.

2025-01-16 08:05 UTC, valentin-mladenov requested changes
Waiting for file picking algorithm to be revised.

2025-01-16 12:33 UTC, kevinbuhmann commented
> Waiting for file picking algorithm to be revised.

That has already been done. See 6b7e7b9c73ccb21804948131681e18e8025a482e.

2025-01-17 13:28 UTC, valentin-mladenov approved these changes
LGTM

Check my comments and implement them if the suggestions make better sense than current variant.
Directly resole them when completed.

2025-01-17 13:28 UTC, valentin-mladenov commented on projects/angular/src/forms/file-input/file-input-container.ts
> +    const existingFiles = Array.from(this.fileInput.elementRef.nativeElement.files);
No point to create array from the `FileList`. You can still iterate over it.

```suggestion
    const existingFiles = this.fileInput.elementRef.nativeElement.files;
```

2025-01-17 13:28 UTC, valentin-mladenov commented on projects/angular/src/forms/file-input/file-input-container.ts
> +    for (const existingFile of existingFiles) {
Move `existingFiles` creation closer to the loop for better visiblity.
```suggestion
    // add existing files if a new file doesn't have the same name
    const existingFiles = this.fileInput.elementRef.nativeElement.files;
    for (const existingFile of existingFiles) {
```

Technically can remove the local `const` altogether.
```suggestion
    // add existing files if a new file doesn't have the same name
    for (const existingFile of this.fileInput.elementRef.nativeElement.files) {
```

2025-01-17 13:57 UTC, kevinbuhmann commented on projects/angular/src/forms/file-input/file-input-container.ts
> +    for (const existingFile of existingFiles) {
Yeah, I think I agree. I'll simplify this. Thanks!

2025-01-17 13:57 UTC, kevinbuhmann commented on projects/angular/src/forms/file-input/file-input-container.ts
> +    const existingFiles = Array.from(this.fileInput.elementRef.nativeElement.files);
Good catch. Thanks!

2025-01-17 16:48 UTC, merged