feat(datagrid): add possbility to clear filters
vmware-clarity/ng-clarity pull request #246
Opened 2022-07-19 07:05 UTC by derkoe

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)  
  I could not find the sources for https://clarity.design/documentation/datagrid/structure
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Now, you cannot easily clear a filter. For string filters you have to delete all chars in the field, for number filters you have to click both fields and clear them

Issue Number: #225

## What is the new behavior?

There is a new clear button added to the filter in the Datagrid which clears the current filter

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-07-19 13:43 UTC, kevinbuhmann requested changes

2022-07-19 16:02 UTC, ashleyryan commented
We need to get @colinreedmiller involved since this includes a visual change (and a slightly breaking one at that)

2022-07-19 16:10 UTC, colinreedmiller commented
'Does this PR introduce a breaking change?' checkbox indicates no breaking change - does need to be updated?
Please add me as a reviewer.

2022-07-19 19:20 UTC, derkoe commented on projects/angular/src/utils/i18n/common-strings.default.ts
> +  delete: 'Delete',
I wanted to reuse the existing definitions in ClrCommonStrings but I can add "clear" if you want to.

2022-07-19 19:21 UTC, ashleyryan commented
@colinreedmiller  this PR came out of this discussion - I think it's a visual breaking change based on the  screenshot?

2022-07-19 19:27 UTC, derkoe commented on projects/angular/src/data/datagrid/datagrid-filter.ts
> -
Re-added the blang line

2022-07-19 19:31 UTC, colinreedmiller commented
Thanks for the screenshot @ashleyryan - Yes, this is visually breaking and a design change more generally. UX needs to look at this before moving ahead.

2022-07-19 20:23 UTC, kevinbuhmann commented on projects/angular/src/utils/i18n/common-strings.default.ts
> +  delete: 'Delete',
Yeah, I think we should add `clear` for this.

2022-07-20 06:17 UTC, derkoe commented on projects/angular/src/utils/i18n/common-strings.default.ts
> +  delete: 'Delete',
Changed text to 'Clear'

2022-07-20 15:26 UTC, kevinbuhmann commented on projects/angular/src/utils/i18n/common-strings.default.ts
> +  delete: 'Delete',
This line should be removed as it not needed for this change.

2022-07-21 05:38 UTC, derkoe commented on projects/angular/src/utils/i18n/common-strings.default.ts
> +  delete: 'Delete',
Removed the line + rebased

2022-07-29 17:41 UTC, Partick commented
Is it possible to share the visual design via a screenshot? I need to see a working demo before I can provide feedback.

2022-07-29 17:58 UTC, kevinbuhmann commented
This should be added to demo (or storybook, but we don't have datagrid filters in the storybook yet) so that @Partick can see a working demo via the preview link.

2022-07-29 17:59 UTC, kevinbuhmann commented
I think we have filters in the demo app, but this build is failing. @derkoe Please fix the build errors, so that @Partick can see a live demo via the preview link.

2022-07-29 20:00 UTC, derkoe commented
Fixed the build - @Partick you can see the working demo here https://246--storybook-clarity-design.netlify.app/?path=/story/datagrid-column--default

2022-08-17 06:30 UTC, derkoe commented
@Partick any updates on this?

2022-08-17 21:10 UTC, colinreedmiller approved these changes

2022-08-19 14:07 UTC, d-m-s commented
it has been a month since the contribution attempt ... 
can we help speed things up a little?

2022-08-19 14:10 UTC, d-m-s commented
> Is it possible to share the visual design via a screenshot? I need to see a working demo before I can provide feedback.

also discussed upfront:
https://github.com/vmware-clarity/ng-clarity/discussions/225

working demo as already posted here
https://246--storybook-clarity-design.netlify.app/?path=/story/datagrid-column--default

2022-08-26 14:25 UTC, ashleyryan commented
Heads up on this - there has been a lot of PTO with summer vacations the last month or so. Design is currently looking at this, there's some concerns about the popup in a popup behavior

2022-08-26 15:20 UTC, derkoe commented
> Design is currently looking at this, there's some concerns about the popup in a popup behavior

Which popup? This change only adds the trash can to clear the filter.

2022-08-26 15:21 UTC, ashleyryan commented
> Which popup? This change only adds the trash can to clear the filter.

Oops, I commented on the wrong PR. Design is looking at this one too

2022-08-29 05:44 UTC, derkoe commented
BTW this the current UX of clearing filters. For numbers you have to first focus the lower bounds, clear the field, then focus the upper bound and clear the field; then close the filter.

![Clarity-Datagrid-clear-filter](https://user-images.githubusercontent.com/123199/187130843-fea47835-7ec1-450d-a8da-5b79bfd8705a.gif)

2022-10-05 07:16 UTC, derkoe commented
Any news on this? 

If this will not be merged, can we at least export [`CustomFilter`](https://github.com/vmware-clarity/ng-clarity/blob/main/projects/angular/src/data/datagrid/providers/custom-filter.ts) from Clarity? Then we can create our own clearable datagrid filter component.

2022-11-28 15:40 UTC, poifir commented
@colinreedmiller As you're currently the assigned person I'd like to ask how we can help to speedup the progress a little bit? Thanks :)

2022-12-06 14:10 UTC, poifir commented
> @colinreedmiller As you're currently the assigned person I'd like to ask how we can help to speedup the progress a little bit? Thanks :)

Hello @Partick  - I just noticed you're in the lead now :D - please tell me what is missing to get this PR merged. Thanks :)

2023-01-09 15:37 UTC, d-m-s commented
any updates to this issue?
@Partick

2025-03-04 12:00 UTC, LynxDelli commented
Clarity Design is working on new filter functionality, therefore, this is absolute.

2025-03-04 12:00 UTC, closed without merging