chore: widen angular peer deps
vmware-clarity/ng-clarity pull request #248
Opened 2022-07-20 18:27 UTC by hippee-lee

Signed-off-by: Matthew Hippely <hippely@gmail.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe:

## What is the current behavior?
To use @clr/angular with @angular/*@14 it currently requires an `npm i --force` which is not ideal. 
This came up when upgrading an application to latest angular versions because of a finding during a security review. 

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-07-20 18:33 UTC, kevinbuhmann requested changes
Thanks! This should be a `feat`, not a `chore`, so that it triggers a new release.

2022-07-20 18:36 UTC, kevinbuhmann commented
I recommend `feat: allow applications to use angular 14` (or similar) for the commit message so the changelog is more clear.

2022-07-21 15:56 UTC, ashleyryan approved these changes

2022-07-21 17:06 UTC, kevinbuhmann approved these changes

2022-07-21 17:11 UTC, merged