feat: add demo for tree-view-type-ahead
vmware-clarity/ng-clarity pull request #39
Opened 2022-03-23 15:55 UTC by Shijir

Signed-off-by: stsogoo <stsogoo@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-03-28 16:54 UTC, mathisscott requested changes

2022-03-28 16:54 UTC, mathisscott commented on projects/angular/src/data/tree-view/tree-node.ts
> +    this.subscriptions.push(
Check out the `takeUntil/destroy` pattern [in this PR](https://github.com/vmware-clarity/ng-clarity/pull/42)

2022-03-28 16:54 UTC, mathisscott commented on projects/angular/src/data/tree-view/tree-focus-manager.service.ts
> +  private findClosestNodeStartsWith(searchString: string, model: TreeNodeModel<T>): TreeNodeModel<T> {
Seems like the return type should be `TreeNodeModel<T> | null`

2022-04-01 20:01 UTC, Shijir commented
Closing this PR as a topic branch PR is created instead: https://github.com/vmware-clarity/ng-clarity/pull/61

2022-04-01 20:01 UTC, closed without merging