feat(wizard): support custom main title and page titles
vmware-clarity/ng-clarity pull request #640
Opened 2023-04-18 07:28 UTC by dtsanevmw

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)
- [X] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

The main title was wrapped up around h2 element and even adding a custom one it was still inside h2.

Issue Number: CDE-128

## What is the new behavior?

Added support for both custom templates and inputs ( clrWizardTitle, clrWizardPageTitle, clrWizardPageNavTitle ). 

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2023-04-18 14:10 UTC, kevinbuhmann requested changes

2023-04-18 14:10 UTC, kevinbuhmann commented on projects/angular/src/wizard/wizard.html
> +    <ng-content select="clr-wizard-title"></ng-content>
I believe this is a breaking change. If a consumer doesn't change their application code, the heading element will be lost.

2023-04-18 14:11 UTC, kevinbuhmann requested changes

2023-04-18 14:11 UTC, kevinbuhmann commented on projects/angular/src/wizard/wizard.html
> +    <ng-content select="clr-wizard-title"></ng-content>
I believe this is a breaking change. If a consumer doesn't change their application code, the heading element will be lost.

2023-04-27 16:04 UTC, kevinbuhmann commented on projects/angular/src/wizard/wizard-page-title.ts
> +  isIncludingHeadingElements = false;
I would rename this to `includesHeadingElements`.

2023-04-27 16:08 UTC, kevinbuhmann commented on projects/angular/src/wizard/wizard.html
> +    <ng-content select="clr-wizard-title"></ng-content>
Can we move the `clr-wizard-title` CSS class to a wrapper span/div so that users don't have to include that class on custom heading elements?

2023-04-27 16:08 UTC, kevinbuhmann commented on projects/angular/src/wizard/wizard.html
> +    <ng-content select="clr-wizard-title"></ng-content>
Same thing for the `id`.

2023-04-27 19:40 UTC, kevinbuhmann requested changes
If an `h2` (the default) is projected for `clrPageTitle`, this happens:

![image](https://user-images.githubusercontent.com/7399499/234964651-f14f42ec-3ab6-496f-9d95-25f469d2c054.png)

The stepnav shouldn't have large text like this. Also, there are some heading alignment changes in the visual snapshots.

  I took a stab at this, and I think I found a simpler solution that doesn’t introduce any visual changes. Please take a look at 40cc8e8091fedd60f3b0ca33cd017d13bbe9e04a. If you like my solution, I think we should take it instead.

2023-04-28 15:45 UTC, dtsanevmw commented on projects/angular/src/wizard/wizard.html
> +    </div>
I started with the idea to leave the styling to whoever uses these custom styles. But I like the idea to have consistent styles for all headings and to be used just for a11y. I added couple of css rules that should handle these cases.

2023-05-03 17:56 UTC, kevinbuhmann commented on projects/angular/src/wizard/wizard.html
> +  <div class="modal-title">
I think this change introduces visual changes. I would keep the heading element here for this change. There should not be any visual changes here. This PR should be scoped to just the custom heading levels. I have WIP on the wizard redesign that moves that header actions.

2023-05-03 19:37 UTC, kevinbuhmann commented on projects/angular/src/wizard/wizard.html
> +    <div class="clr-wizard-title" role="heading" [attr.aria-level]="wizardTitle.headingLevel" id="{{wizardId}}">
This causes an incorrect visual change as well.

2023-05-03 19:38 UTC, kevinbuhmann commented on projects/angular/src/wizard/wizard-title.ts
> +  @Input('clrHeadingLevel') headingLevel: '1' | '2' | '3' | '4' | '5' | '6' = '1';
This should support numbers as well. I would add a `heading-level.ts` file with the following:

```typescript
export type HeadingLevel = 1 | 2 | 3 | 4 | 5 | 6 | '1' | '2' | '3' | '4' | '5' | '6';
```

2023-05-03 20:15 UTC, kevinbuhmann requested changes
See comments. This PR should not have any visual changes. Also, the storybook should be updated and unit tests are needed.

See ea7d71450b8dc9988cfd2d894cb0fec6be6c8d37 for a working implementation with these changes and without visual changes.

2023-05-04 11:51 UTC, kevinbuhmann requested changes

2023-05-04 11:51 UTC, kevinbuhmann commented on projects/angular/src/wizard/wizard.html
> -
Please put this blank line back.

2023-05-04 11:51 UTC, kevinbuhmann commented on projects/angular/src/wizard/_wizard.clarity.scss
> +    .clr-wizard-page-title {
These styles are not used or needed.

2023-05-04 12:03 UTC, kevinbuhmann commented on projects/angular/src/wizard/index.ts
> -export * from './wizard-custom-tags';
This file should be deleted.

2023-05-04 12:46 UTC, kevinbuhmann approved these changes

2023-05-09 07:23 UTC, merged