chore: accordion documentation for css
vmware-clarity/ng-clarity pull request #738
Opened 2023-06-02 11:33 UTC by mindarelus

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-06-02 12:18 UTC, dtsanevmw commented on projects/angular/src/accordion/STYLES.md
> +## CSS Properties
```suggestion
## CSS Custom Properties
```

2023-06-02 12:19 UTC, dtsanevmw commented on projects/angular/src/accordion/STYLES.md
> +| CSS Property Name                             | Description                                                           |
```suggestion
| CSS Custom property                             | Description                                                           |
```

2023-06-02 12:19 UTC, dtsanevmw requested changes
I would recommend to remove repeatable words like "Respresents" in the classes and "The" from properties to be consistent. Also I see that there are 20 css properties for accordion in the project but here they are 10.

2023-06-08 16:20 UTC, kevinbuhmann reviewed
I added a new class in #739: `clr-accordion-content-region`.

2023-06-09 12:44 UTC, dtsanevmw approved these changes

2023-06-09 14:19 UTC, merged