chore(button group): add style documentation
vmware-clarity/ng-clarity pull request #752
Opened 2023-06-06 13:56 UTC by valentin-mladenov

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-06-06 14:30 UTC, dtsanevmw commented on projects/angular/src/button/button-group/STYLE.md
> +| btn-icon-link         | Used to indicate button icon links in button group.            |
```suggestion
| btn-link | Used with `btn-group`  for flat buttons group.            |
| btn-icon-link | Used with `btn-group` and `btn-link`  for flat icon buttons group.            |
```

2023-06-06 14:31 UTC, dtsanevmw commented on projects/angular/src/button/button-group/STYLE.md
> +| clr-icon-title        | Used to indicate button icon title in button group.            |
```suggestion
| clr-icon-title        | A11y class to add text for a button with icon only so it can be read from screen reader.            |
```

2023-06-06 14:32 UTC, dtsanevmw commented on projects/angular/src/button/button-group/STYLE.md
> +| clr-button-group-menu | Internal class for opening the dropdown menu for button group. |
```suggestion
| clr-button-group-menu | Internal class for button group menu content |
```

2023-06-06 14:33 UTC, dtsanevmw requested changes
Left some comments about the descriptions

2023-06-07 06:11 UTC, valentin-mladenov commented on projects/angular/src/button/button-group/STYLE.md
> +| clr-button-group-menu | Internal class for opening the dropdown menu for button group. |
corrected in commit 80f0422

2023-06-07 06:11 UTC, valentin-mladenov commented on projects/angular/src/button/button-group/STYLE.md
> +| clr-icon-title        | Used to indicate button icon title in button group.            |
corrected in commit 80f0422

2023-06-07 06:11 UTC, valentin-mladenov commented on projects/angular/src/button/button-group/STYLE.md
> +| btn-icon-link         | Used to indicate button icon links in button group.            |
corrected in commit 80f0422

2023-06-07 07:18 UTC, dtsanevmw approved these changes

2023-06-07 07:33 UTC, merged