feat(textarea): tokens
vmware-clarity/ng-clarity pull request #799
Opened 2023-07-05 14:45 UTC by mindarelus

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-07-10 07:36 UTC, valentin-mladenov requested changes
Check my comments.

2023-07-10 07:36 UTC, valentin-mladenov commented on projects/angular/src/forms/styles/_properties.forms.scss
> +        2;
```suggestion
      --clr-forms-textarea-padding: #{forms-variables.$clr-forms-baseline} +
        #{variables.$clr_baselineRem_2px}
        #{forms-variables.$clr-forms-baseline} *
        2;
```

Consider my suggestion.

2023-07-10 07:36 UTC, valentin-mladenov commented on projects/angular/src/forms/styles/_textarea.clarity.scss
> +      variables.$clr-use-custom-properties
The variables are not needed any more use their values directly. Brackets are optional.

```suggestion
    (forms-variables.$clr-forms-baseline + variables.$clr_baselineRem_2px) (forms-variables.$clr-forms-baseline * 2),
      variables.$clr-use-custom-properties
```

2023-07-10 07:36 UTC, valentin-mladenov commented on projects/angular/src/forms/styles/_textarea.clarity.scss
>      &:focus {
Here you have to calculate selected status from figma using border color `--cds-alias-object-interaction-background-highlight`

2023-08-01 08:14 UTC, dtsanevmw commented on projects/angular/src/forms/styles/_textarea.clarity.scss
> +      // margin-top: 0;
That's needed for textarea in horizontal forms.

2023-08-01 08:16 UTC, dtsanevmw requested changes
Revert the deletion of `margin-top` for the horizontal state and it seems that the text area is now misaligned and the subtext starts before it 
![Screenshot 2023-08-01 at 11 14 39](https://github.com/vmware-clarity/ng-clarity/assets/127101685/d416af88-1119-404c-8e5b-b27ddca5284d)

2023-08-01 09:41 UTC, dtsanevmw approved these changes

2023-08-01 11:17 UTC, valentin-mladenov approved these changes
LGTM

2023-08-01 11:17 UTC, merged