Spinner token migration
vmware-clarity/ng-clarity pull request #850
Opened 2023-08-03 12:38 UTC by mivaylo

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-08-03 12:40 UTC, mivaylo commented
CDE-604

2023-08-07 10:26 UTC, valentin-mladenov requested changes
Check my comments.

2023-08-07 10:26 UTC, valentin-mladenov commented on projects/angular/src/progress/spinner/STYLES.md
> +| --clr-spinner-spacing-to-text          | Spacing between spinner and text next to it  |
Can you rename this to `--clr-spinner-margin-right`?
There may be anything on the right not only text.

2023-08-07 10:26 UTC, valentin-mladenov commented on projects/angular/src/progress/spinner/_properties.spinner.scss
> +  }
Add those as properties.

```suggestion
    --clr-spinner-fill-bg-color: rgba(#{spinner-variables.$clr-spinner-bg-color}, #{spinner-variables.$clr-spinner-opacity});
    --clr-spinner-fill-inverse-bg-color: : rgba(#{spinner-variables.$clr-spinner-inverse-bg-color}, 0.15);
    --clr-spinner-fill-color: #{spinner-variables.$clr-spinner-color};
    --clr-spinner-fill-inverse-color: #{spinner-variables.$clr-spinner-inverse-color};
  }
```

2023-08-07 10:26 UTC, valentin-mladenov commented on projects/angular/src/progress/spinner/_spinner.clarity.scss
> +      border-radius: 50%;
This should be extracted as a property token. 
```suggestion
      @include mixins.css-var(
        border-radius,
        clr-spinner-radius,
        50%,
        variables.$clr-use-custom-properties
      );
```
Add it in properties and shim as:
Prop: `--clr-spinner-radius: 50%;` 
Shim: `--clr-spinner-radius: var(--cds-alias-object-border-radius-300);`

2023-08-07 10:26 UTC, valentin-mladenov commented on projects/angular/src/progress/spinner/_spinner.clarity.scss
> +      border-radius: 50%;
This should be extracted as a property token. Same as previous comment.
```suggestion
      @include mixins.css-var(
        border-radius,
        clr-spinner-radius,
        50%,
        variables.$clr-use-custom-properties
      );
```
Add it in properties and shim as:
Prop: `--clr-spinner-radius: 50%;` 
Shim: `--clr-spinner-radius: var(--cds-alias-object-border-radius-300);`

2023-08-07 10:26 UTC, valentin-mladenov commented on projects/angular/src/progress/spinner/_spinner.clarity.scss
> +      margin-right: var(--clr-spinner-spacing-to-text);
Use it with mixins.
```suggestion      
      @include mixins.css-var(
        margin-right,
        clr-spinner-spacing-to-text,
        0,
        variables.$clr-use-custom-properties
      );
```

2023-08-08 13:02 UTC, merged