feat(alerts): tokens implementation
vmware-clarity/ng-clarity pull request #869
Opened 2023-08-09 13:25 UTC by mindarelus

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-08-11 17:04 UTC, Jinnie requested changes

2023-08-11 17:04 UTC, Jinnie commented on tests/snapshots/alert/alerts--variants-core-dark.png
The black text on dark green in the fourth example carousel looks very suspicious from a11y perspective.

2023-08-11 17:04 UTC, Jinnie commented on projects/angular/src/emphasis/alert/_alert.clarity.scss
> +    // display: inline-block; //needed for IE11
remove commented lines here and the 2 that are couple of line below

2023-08-11 17:04 UTC, Jinnie commented on projects/angular/src/emphasis/alert/_alert.clarity.scss
> +    // .alert-item > span,
remove commented lines

2023-08-14 08:36 UTC, valentin-mladenov commented on tests/snapshots/alert/alerts--variants-core-dark.png
Yeah I noticed it too. The property `clr-app-alert-danger-pager-bg-color` is introduced, but not used.
@mindarelus change this line to use the new property. https://github.com/vmware-clarity/ng-clarity/blob/alert-tokens/projects/angular/src/emphasis/alert/_alert.clarity.scss#L588

2023-08-15 07:13 UTC, valentin-mladenov commented on projects/angular/src/emphasis/alert/_alert.clarity.scss
> +      height: variables.$clr_baselineRem_0_667;
The height must follow 24px icon token.

2023-08-15 07:17 UTC, valentin-mladenov commented on projects/angular/src/emphasis/alert/_alert.clarity.scss
> +    );
We need design for `sm` alerts.

2023-08-15 07:20 UTC, valentin-mladenov commented on projects/angular/src/emphasis/alert/_alert.clarity.scss
>      margin-right: variables.$clr_baselineRem_0_5;
Why do we keep this margin in token migration? 
The spacing is done by `gaps`. Keep it only for NG theme.


```suggestion
```

2023-08-15 07:23 UTC, valentin-mladenov commented on projects/angular/src/emphasis/alert/_alert.clarity.scss
>      .close {
Close icon height and width must be 16px by design.

2023-08-15 14:51 UTC, valentin-mladenov approved these changes
Check the comments regarding property name change. All other LGTM.

2023-08-15 14:51 UTC, valentin-mladenov commented on projects/angular/src/emphasis/alert/_alert.clarity.scss
> +          clr-alert-close-button-dims,
```suggestion
          clr-alert-close-icon-size,
```

2023-08-15 14:51 UTC, valentin-mladenov commented on projects/ui/src/shim.cds-core.scss
> +  --clr-alert-close-button-dims: var(--cds-global-space-7);
```suggestion
  --clr-alert-close-icon-size: var(--cds-global-space-7);
```

2023-08-15 14:51 UTC, valentin-mladenov commented on projects/angular/src/emphasis/alert/_alert.clarity.scss
> +          clr-alert-close-button-dims,
```suggestion
          clr-alert-close-icon-size,
```

2023-08-16 07:26 UTC, dtsanevmw requested changes
Please test or create stories for alerts with actions. It gets broken - check screenshot: 
Before PR changes:
<img width="1549" alt="Screenshot 2023-08-16 at 10 26 06" src="https://github.com/vmware-clarity/ng-clarity/assets/127101685/e51c5f42-a3a6-4704-9f05-e55724222f9d">
After PR changes:
<img width="1488" alt="Screenshot 2023-08-16 at 10 25 44" src="https://github.com/vmware-clarity/ng-clarity/assets/127101685/fef0d581-fbcf-4b0f-9a57-c89894b603bd">

2023-08-16 12:07 UTC, dtsanevmw approved these changes

2023-08-16 13:10 UTC, Jinnie approved these changes
Thanks for the fixes, looks good to me.

2023-08-16 13:34 UTC, merged